// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VocabularyService.Persistence;

#nullable disable

namespace VocabularyService.Persistence.Migrations
{
    [DbContext(typeof(VocabularyDbContext))]
    [Migration("20260524104331_InitialVocabularySchema")]
    partial class InitialVocabularySchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("VocabularyService.Persistence.Entities.BandEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("bands", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Core words for early intermediate learners",
                            Name = "IELTS 5.0",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Words for developing academic fluency",
                            Name = "IELTS 6.0",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Advanced academic vocabulary",
                            Name = "IELTS 7.0",
                            SortOrder = 3
                        });
                });

            modelBuilder.Entity("VocabularyService.Persistence.Entities.ExampleSentenceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("EnglishText")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("VietnameseMeaning")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("VocabularyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VocabularyId");

                    b.ToTable("examples", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            EnglishText = "The national curriculum was updated to include more digital skills.",
                            VietnameseMeaning = "Chuong trinh hoc quoc gia da duoc cap nhat de bo sung ky nang so.",
                            VocabularyId = 1
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 1,
                            EnglishText = "Protecting biodiversity is essential for maintaining ecosystem stability.",
                            VietnameseMeaning = "Bao ve da dang sinh hoc la dieu thiet yeu de duy tri su on dinh cua he sinh thai.",
                            VocabularyId = 2
                        });
                });

            modelBuilder.Entity("VocabularyService.Persistence.Entities.TopicEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("varchar(400)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("topics", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorHex = "#C51E3A",
                            Description = "Academic and school-related vocabulary",
                            Name = "Education"
                        },
                        new
                        {
                            Id = 2,
                            ColorHex = "#8B0000",
                            Description = "Ecology, climate, and sustainability terms",
                            Name = "Environment"
                        },
                        new
                        {
                            Id = 3,
                            ColorHex = "#E54B4B",
                            Description = "Travel, tourism, and culture vocabulary",
                            Name = "Travel"
                        });
                });

            modelBuilder.Entity("VocabularyService.Persistence.Entities.VocabularyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BandId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("PartOfSpeech")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("Pronunciation")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("BandId");

                    b.HasIndex("TopicId", "Word")
                        .IsUnique();

                    b.ToTable("vocabularies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BandId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Meaning = "chuong trinh hoc",
                            PartOfSpeech = "noun",
                            Pronunciation = "/kəˈrɪk.jə.ləm/",
                            TopicId = 1,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Word = "curriculum"
                        },
                        new
                        {
                            Id = 2,
                            BandId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Meaning = "da dang sinh hoc",
                            PartOfSpeech = "noun",
                            Pronunciation = "/ˌbaɪ.əʊ.daɪˈvɜː.sə.ti/",
                            TopicId = 2,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Word = "biodiversity"
                        });
                });

            modelBuilder.Entity("VocabularyService.Persistence.Entities.ExampleSentenceEntity", b =>
                {
                    b.HasOne("VocabularyService.Persistence.Entities.VocabularyEntity", "Vocabulary")
                        .WithMany("Examples")
                        .HasForeignKey("VocabularyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vocabulary");
                });

            modelBuilder.Entity("VocabularyService.Persistence.Entities.VocabularyEntity", b =>
                {
                    b.HasOne("VocabularyService.Persistence.Entities.BandEntity", "Band")
                        .WithMany("Vocabularies")
                        .HasForeignKey("BandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VocabularyService.Persistence.Entities.TopicEntity", "Topic")
                        .WithMany("Vocabularies")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Band");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("VocabularyService.Persistence.Entities.BandEntity", b =>
                {
                    b.Navigation("Vocabularies");
                });

            modelBuilder.Entity("VocabularyService.Persistence.Entities.TopicEntity", b =>
                {
                    b.Navigation("Vocabularies");
                });

            modelBuilder.Entity("VocabularyService.Persistence.Entities.VocabularyEntity", b =>
                {
                    b.Navigation("Examples");
                });
#pragma warning restore 612, 618
        }
    }
}
